// <auto-generated />
namespace AndyTools.Wpf
{
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    using AndyTools.Annotations;

    public class ViewModelBase : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        [NotifyPropertyChangedInvocator]
        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            this.PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
